title: something something hexadecimal
author: beckler
subtitle: thoughts from an digital entropy wizard

url: "https://adc.io"
baseurl: ""

footer_only_homepage: true
footer_url: "https://github.com/beckler"
footer_text: "behold! some code!"

profile-picture: assets/profile.png
favicon_location: assets/favicon.png

permalink: /:year-:month-:day-:title/
sass:
  style: compressed
  sass_dir: css

navbar:
  - name: "About"
    link: "about"
