baseurl = "https://adc.io/"
title = "adc.io"
theme ="base16"
languageCode = "en-us"
googleAnalytics = "UA-51842603-4"
enableEmoji = true

[blackfriday]
    hrefTargetBlank = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true